### PR TITLE
Fix TypeError: not enough arguments for format string at search method

### PR DESCRIPTION
**Pull request by s0x90**

### CODE REVIEW

**Comment by svartalf** [comment]
I'm not sure why it should be "fixed", `point` value must be a list (or tuple) with a two elements in it.

Is your point three-dimensional? :)

**Comment by s0x90** [comment]
Hi @svartalf ,
Thank you for your open source contribution. 

I get the error `TypeError: not enough arguments for format string` when I'm using `.search()` method 

``` python
import dgis
client = dgis.API(DGIS-KEY)
client.search(what=u'пиво', point=[56.001573, 54.7069285], radius=1000, sort='distance')
```

It seems that the problem caused you are formatting the string with two arguments `'%s,%s'`, but passing only one - `point`

https://github.com/svartalf/python-2gis/blob/master/dgis/__init__.py#L70

**Comment by svartalf** [comment]
Well, yeah, you are right, `list` type had failed us:

```
$ python2
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> '%s,%s' % [56.001573, 54.7069285]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not enough arguments for format string
>>> '%s,%s' % (56.001573, 54.7069285)
'56.001573,54.7069285'
```

**Comment by s0x90** [comment]
Yes, it works with `tuple`, but failed with `list`. Are you going to accept PR? Or I can just use `tuple` otherwise.

**Comment by svartalf** [comment]
I'm gonna merge and publish it onto a PyPI later today, so if you can wait a little bit.. :)

**Comment by s0x90** [comment]
Sure, thank you again :)

**Comment by svartalf** [comment]
Sorry for a delay. I had merged PR and uploaded new package onto a PyPI (1.3.1 version).

Wheels also!

**Pull request merged**
